import path from 'path';

export interface QCMonitorConfig {
  /** Base URL of your QC Monitor API, e.g. http://localhost:3001 */
  apiUrl: string;
  /** Team API key generated by POST /api/teams */
  apiKey: string;
  /** Team name (informational only, not sent to API) */
  teamName?: string;
  /** Number of retry attempts on network failure (default: 2) */
  retries?: number;
  /** Capture and upload screenshots on failure (default: true) */
  captureScreenshot?: boolean;
  /** Capture and upload videos on failure (default: true) */
  captureVideo?: boolean;
  /** Capture and upload traces on failure (default: true) */
  captureTrace?: boolean;
}

const CONFIG_FILES = [
  'qc-monitor.config.ts',
  'qc-monitor.config.js',
  'qc-monitor.config.mjs',
  'qc-monitor.config.cjs',
];

async function tryLoadFile(): Promise<Partial<QCMonitorConfig>> {
  for (const file of CONFIG_FILES) {
    try {
      const filePath = path.resolve(process.cwd(), file);
      // Dynamic import works for .js/.mjs/.cjs directly; for .ts it requires
      // a loader (ts-node, tsx, or Playwright's built-in transpiler).
      const mod = await import(filePath) as { default?: Partial<QCMonitorConfig> } | Partial<QCMonitorConfig>;
      return ('default' in mod && mod.default ? mod.default : mod) as Partial<QCMonitorConfig>;
    } catch {
      // File not found or not loadable — try next
    }
  }
  return {};
}

/**
 * Merge config from (in priority order, highest first):
 *   1. Environment variables
 *   2. qc-monitor.config.{ts,js,mjs,cjs} in project root
 *   3. Hard-coded defaults
 */
export async function loadConfig(overrides: Partial<QCMonitorConfig> = {}): Promise<QCMonitorConfig> {
  const fileConfig = await tryLoadFile();

  return {
    apiUrl:
      overrides.apiUrl ||
      process.env['QC_MONITOR_API_URL'] ||
      fileConfig.apiUrl ||
      '',
    apiKey:
      overrides.apiKey ||
      process.env['QC_MONITOR_API_KEY'] ||
      fileConfig.apiKey ||
      '',
    teamName: overrides.teamName ?? fileConfig.teamName,
    retries: overrides.retries ?? fileConfig.retries ?? 2,
    captureScreenshot: overrides.captureScreenshot ?? fileConfig.captureScreenshot ?? true,
    captureVideo: overrides.captureVideo ?? fileConfig.captureVideo ?? true,
    captureTrace: overrides.captureTrace ?? fileConfig.captureTrace ?? true,
  };
}
